### ISSUE TITLE
Use a maintained tree-sitter grammar for Swift

### ISSUE THREAD

**Issue by evrsen** [samuser107/zed-swift-extension#2]
The current tree-sitter grammar for Swift being used is abandoned, this issue proposes the use of [tree-sitter-swift](https://github.com/alex-pinkus/tree-sitter-swift) by Alex instead.

**Comment by samuser107** [comment]
> The current tree-sitter grammar for Swift being used is abandoned, this issue proposes the use of [tree-sitter-swift](https://github.com/alex-pinkus/tree-sitter-swift) by Alex instead.

The tree-sitter you mentioned is not well build for Zed... If you have any tips to make it compatible i'm open to them.

**Comment by evrsen** [comment]
> The tree-sitter you mentioned is not well build for Zed... If you have any tips to make it compatible i'm open to them.

Yeah there seems to be some missing files along with other issues, I tried fixing it myself and gave up as I have no previous experience with tree-sitter, hoping someone more experienced can take a look. Getting a maintained tree-sitter grammar should still be prioritised and I'm not sure of any others. Just in case you haven't followed but a PR was merged to Zed that fixed the crash with this swift extension due to an old tree-sitter version being used for the grammar;  https://github.com/zed-industries/zed/pull/8306.

What I tried was forking the proposed ``tree-sitter-swift`` repository and generate the missing files myself running ``tree-sitter generate`` and remove them from ``.gitignore``, that way it has all the files Zed seems to want, I believe I then had some problems with emscripten when trying to build the wasm running ``tree-sitter build-was`` (which is a required step for the extension to work) I got errors about it not being able to target a platform. Maybe you can reproduce and see if you can figure it out?

**Comment by tonycoco** [comment]
Pinging @alex-pinkus here.

**Comment by alex-pinkus** [comment]
If by “the missing files” you mean the generated `parser.c`, `grammar.json`, etc, it is intentional that we don’t check those into main. Note that the tree-sitter 1.0 checklist plans to “remove generated files from all the grammar repos in the tree-sitter org” so at some point Zed will ostensibly stop relying on those.

In the short term, there’s an alternate branch called `with-generated-files` that gets autoupdated on every release. If you have any issues due to files that aren’t on that branch then let me know and I’ll be happy to add them.

**Comment by samuser107** [comment]
Thank you so much! With the branch you mentionned it passes zed's tests so i hope it will now work properly.
